services:
  - type: web
    name: puppeteer-pdf
    env: node
    plan: starter
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 8080