services:
  - type: web
    name: puppeteer-pdf
    env: node
    plan: starter
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node server.js
    envVars:
      - key: PORT
        value: "3000"
      - key: PUPPETEER_CACHE_DIR
        value: "/workspace/.cache/puppeteer"
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "false"

